
    <section class="centrado" id="intro">
        <div id="wrapper">
            <div>
                <h1>Hola, astronauta</h1>
            </div>
            <div>
                Bienvenido a la página con la mejor colección de naves espaciales del siglo XXI. 
            </div>
            <div class="buttons">
                <a href="" class="button">Compra tu primera nave</a>
            </div>
        </div>
    </section>
