<!DOCTYPE html>
<!--**
 * * Descripción: Cabecera portal Programa Aprender PHP
 * *
 * * Descripción extensa: Pagina web dividida en 4 ficheros.
 * *
 * * @author  Lola <dllido@uji.es>
 * * @version 1
 * * @link http://dllido@al.nisu.org/P0/holaMundo.php
 * * -->
<html>
<head>
	<meta charset="UTF-8">
	<title>Bienvenido a la web de ACCE</title>
	<META name="Author" content="AlumnoXXX">
	<link rel="stylesheet" href="./css/header.css" type="text/css">
	<link rel="stylesheet" href="./css/estilo.css" type="text/css">
</head>

<body>
	<header>
		<div class="container">
			
			<ul class="navRoot">
				<li class="navSection logo">
					<img src="./img/Spaceship_1.png" id="logo" alt="logo" height="50"/>
				</li>
				<li class="navSection primary">
					<a class="rootLink" href="index.php">Home</a>
					<a class="rootLink" href="?module=shop">Tienda</a>
					<a class="rootLink" href="?module=game">Juego</a>
					
				</li>
				<li class="navSection secondary">
					<a class="rootLink" href="">Contact</a>
					<a class="rootLink" href="">Iniciar sesión</a>
				</li>
			</ul>
			
		</div>
	</header>
	
	
