<!DOCTYPE html>
<!--**
 * * Descripción: Cabecera portal Programa Aprender PHP
 * *
 * * Descripción extensa: Pagina web dividida en 4 ficheros.
 * *
 * * @author  Lola <dllido@uji.es>
 * * @version 1
 * * @link http://dllido@al.nisu.org/P0/holaMundo.php
 * * -->
<html>
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Spaceship X</title>
	<META name="Author" content="AlumnoXXX">
	<script defer src="https://use.fontawesome.com/releases/v5.0.2/js/all.js"></script>
	<script>
  		FontAwesomeConfig = { searchPseudoElements: true };
	</script>
	<link rel="icon" href="./favicon.png">
	<link rel="stylesheet" href="./css/header.css" type="text/css">
	<link rel="stylesheet" href="./css/estilo.css" type="text/css">
	<link rel="stylesheet" href="./css/shop.css" type="text/css">
	<script src="./js/header.js" async defer></script>
	<script src="./js/portal.js" async defer></script>
	<script src='./modules/shx_user/js/user.js' async defer></script>
	<script src='./modules/shx_shop/js/shop.js' async defer></script>
	<script src='./modules/shx_game/js/game.js' async defer></script>
</head>
<body>
	<header>
		<div class="container">
			
			<ul class="navRoot">
				<li class="navSection logo">
					<img src="./img/logo_header.png" id="logo" alt="logo" height="50"/>
				</li>
				<li class="navSection primary">
					<a class="rootLink" href="index.php">Inicio</a>
					<a class="rootLink" href="?module=shop">Tienda</a>
					<a class="rootLink" href="?module=game">Juego</a>
					
				</li>
				<li class="navSection secondary">
					<a class="rootLink" href="">Contacto</a>
					<a class="rootLink" href="?module=user&action=login">
						<?= $_SESSION["username"] ?? "Iniciar sesión" ?>
					</a>
				</li>
			</ul>
			
		</div>
	</header>
	<main class="content">
	
	
