<main class="content">
    <div class="container">
        <h1>Users</h1>
        <table border="1">
            <thead>
                <th>Usuario</td>
                <th>Nombre</td>
                <th>Email</td>
                <th>Mod.</td>
                <th>Del.</td>
            </thead>
            <tbody>
            <? foreach ($data['users'] as $user): ?>
            <tr>
                <td><?= $user['username']?></td>
                <td><?= $user['name']?></td>
                <td><?= $user['email']?></td>                
                <td><a href="?module=admin&action=mod&id=<?= $user['id'] ?>">&#9998;</a></td>
                <td><a href="?module=admin&action=delete&id=<?= $user['id'] ?>">&#10006;</a></td>
            </tr>
            <? endforeach; ?>
            </tbody>
        </table>
        <h1><a href="?module=admin&action=upload">Añadir un nuevo producto/nave</a></h1>
    </div>    
</main>