<main>
    <div class="centrado" id="login">
        <form action="" method="post" id="login-box" enctype='multipart/form-data'>
            <h3>Nueva nave de combate</h3>            
            <label for="username">Nombre de usuario:</label>
            <input type="text" name="username" id="username">
            <label for="name">Nombre:</label>
            <input type="text" name="name" id="name">
            <label for="email">Email:</label>
            <input type="text" name="email" id="email">
            <label for="passwd">Imagen:</label>
            <input type="file" name="imagen" id="upload-input"/>
            <input type="submit" value="Registrate">
        </form>
    </div>
</main>