<main>
    <div class="centrado" id="login">
        <form action="" method="post" id="login-box" enctype='multipart/form-data'>
            <h3>Nueva nave de combate</h3>            
            <label for="name">Nombre:</label>
            <input type="text" name="name" id="name">
            <label for="descr">Descripcion:</label>
            <input type="text" name="descr" id="descr">
            <label for="imagen">Imagen:</label>
            <input type="file" name="imagen" id="upload-input"/>
            <input type="submit" value="Registrate">
        </form>
    </div>
</main>
