<main class="content">
    <div class="container">
        <h1>Tienda</h1>
        <div class="naves"></div>
    </div>    
    <template>
        <div class="nave">
            <div class="name"></div>
            <img src="//:0" alt="" width="125">           
            <div class="level"></div>
            <div class="type">BÁSICO</div> 
            <div class="stats">
                <span>Stats: </span>
                <span class="health"></span>
            </div>  
            <div class="descr"></div>                      
            <div class="price"></div>
            <div class="buy">Comprar</div>
        </div>                
    </template>
</main>
<script src="./modules/shx_shop/js/shop.js"></script>
