<main class="content">
    <div class="container">
        <h1>Tienda</h1>
        <div class="naves"></div>
    </div>    
    <template>
        <div class="nave">
            <div class="name"></div>
            <div class="level"></div>
            <div class="type"></div>
            <img src="//:0" alt="" width="150">
            <div class="descr"></div>
            <span class="health"></span><img class="h-ico" src="./img/health.svg" width="15" alt="puntos de vida">
            <div class="price"></div>
        </div>                
    </template>
</main>
<script src="./modules/shx_shop/js/shop.js"></script>
