<main>
    <div class="centrado" id="login">
        <div id="login-box">
            <h3>Bienvenido de nuevo</h3>
            <label for="username">Nombre de usuario:</label>
            <input type="text" name="username" id="username">
            <label for="passwd">Contraseña:</label>
            <input type="password" name="passwd" id="passwd">
            <input type="button" value="Iniciar sesión">
            <div id="register">¿Aún no estás registrado? <a href=""> Registrate</a></div>
        </div>
    </div>
</main>
