
<div class="centrado" id="login">
    <form action="" method="post" class="box">
        <h3>Nuevo usuario</h3>            
        <label for="username">Nombre de usuario:</label>
        <input type="text" name="username" id="username">
        <span class="error-msg"><?= $data["error-username"] ?? "" ?></span>
        <label for="name">Nombre:</label>
        <input type="text" name="name" id="name">
        <span class="error-msg"><?= $data["error-name"] ?? "" ?></span>
        <label for="email">Email:</label>
        <input type="text" name="email" id="email">
        <span class="error-msg"><?= $data["error-email"] ?? "" ?></span>
        <label for="passwd">Contraseña:</label>
        <input type="password" name="passwd" id="passwd">
        <span class="error-msg"><?= $data["error-passwd"] ?? "" ?></span>
        <input type="submit" value="Registrate">
    </form>
</div>

